name = "OndaEDF"
uuid = "e3ed2cd1-99bf-415e-bb8f-38f4b42a544e"
authors = ["Beacon Biosignals, Inc."]
version = "0.14.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
EDF = "ccffbfc1-f56e-50fb-a33b-53d1781b2825"
Legolas = "741b9549-f6ed-4911-9fbf-4a1c0c97f0cd"
Onda = "e853f5be-6863-11e9-128d-476edb89bfb5"
OndaEDFSchemas = "9c87d999-769b-4741-85b2-6f554d09e731"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TimeSpans = "bb34ddd2-327f-4c4a-bfb0-c98fc494ece1"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
Compat = "3.32, 4"
EDF = "0.8"
FilePathsBase = "0.9"
Functors = "0.5"
Legolas = "0.5"
Onda = "0.15"
OndaEDFSchemas = "0.2.4"
PrettyTables = "1.3, 2"
SparseArrays = "1"
StableRNGs = "1"
StatsBase = "0.33, 0.34"
Tables = "1.4"
TimeSpans = "0.3, 1"
julia = "1.10"

[extras]
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["FilePathsBase", "Functors", "Test", "Random", "SparseArrays", "StableRNGs", "Statistics"]
